CREATE TABLE LABSCHEMA.CUST (
    CUST_ID INT GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CUST_NAME VARCHAR(100) NOT NULL,
    CUST_ADDRESS VARCHAR(100) NOT NULL,
    CUST_PHONE NUMERIC(10) NOT NULL,
    CUST_EMAIL VARCHAR(100) NOT NULL
) IN DBMATE1.TSMATEDG;
