apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-colocate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: no-colocate
  template:
    metadata:
      labels:
        app: no-colocate
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - no-colocate
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
